### ISSUE TITLE
Missing 'compute_all_solutions' and 'compute_numerical_solutions' modules in utils_figures

### ISSUE THREAD

**Issue by AusCommsteam** [QuentinBrissaud/ML_attenuation_infrasound#2]
Hello

The above modules are missing. They are imported in utils_figures

import compute_all_solutions, compute_numerical_solutions, build_machine_learning

I will look forward to the update.

With thanks,
Tina

**Comment by QuentinBrissaud** [comment]
Thanks Tina, I fixed the broken dependences in utils_figures
